### ISSUE TITLE
Feature Addon : Dub Languages

### ISSUE THREAD

**Issue by 21R01A7263** [Crunchy-DL/Crunchy-Downloader#114]
Hello, there. Great program providing smooth operations overall. But I feel some Quality of Life improvements are underway.

It would be handy to show the current released dub languages in the Downloader itself. Currently I check for the dubs on the crunchyroll series page (`https://www.crunchyroll.com/series/G6J0G49DR/tower-of-god`).

Peace ✌️

**Comment by Vorffeed** [comment]
What you are asking for is already done, if you look in the history file.

![image](https://github.com/user-attachments/assets/aa205a0f-8d73-46ff-9641-5925df5ad3f5)

**Comment by 21R01A7263** [comment]
Pardon me. I failed to present my appeals clearly.

When downloading simulcasts of the ongoing season, it would be neat to know which episodes are dubbed in english, french, etc. on the "Add episodes to queue" screen. 

![image](https://github.com/user-attachments/assets/dde3998f-dcec-4111-b615-369481a4e3e6)

This is a seasonal show being simulcasted. Episodes 8 and 9 are only offered in Japanese as of now. Episodes 1 through 7 are available in simulcast dubs. Hence, a feature to view the available dubs would be handy.

Someone has raised a similar issue #108 previously, the green text aptly describes what I am referring to.

![image](https://github.com/user-attachments/assets/0eaa6f4e-0cbc-4df7-8957-4bc8e26662ee)

**Comment by Vorffeed** [comment]
What you are asking for is shown in the simulcast calendar if you have your region configured, and if you have unchecked hide dubbing you should see what you are asking for.

![image](https://github.com/user-attachments/assets/5c8a61c3-3f5d-4148-9b2d-1b0d4949f93c)

What you are putting is to search for a specific series and if you want it to have a dubbing, if you leave it selected in configuration the language you want to download when you put it in the queue it will download with that dubbing, because in configuration you can mark more than one dubbing language.

![image](https://github.com/user-attachments/assets/4e122498-e5e5-4b2d-aa52-e16ffcc7bb12)

**Comment by Anes-byte** [comment]
Hmm, how do I get the cdm files?

**Comment by R4H4T069** [comment]
> Hmm, how do I get the cdm files?

Search On Google . l3 dumping with Android Studio
