### ISSUE TITLE
Could this be implemented? A button in history that opens the folder of the series in question?

### ISSUE THREAD

**Issue by Vorffeed** [Crunchy-DL/Crunchy-Downloader#118]
I've been asking myself this question for a long time, but I don't know if it can be done by each person's configuration according to what they want the folder where each series in question is stored to be called.

I mean that in the history section, next to the dubbing selection options, another icon should appear which, when clicked, opens the folder where the series in question is stored.

I don't know if this could be implemented, as everyone configures it as they want in the section on how to rename the episodes and folders, in my case I have it like this ${seriesTitle}\\${seriesTitle} - ${episode}. (goes with double \ I don't know why here only one comes out xd)
The only way I can think of would be to save in some log when downloading an episode for the first time the address of the destination folder and then associate it to that tab so that when you click on it, it opens the folder of the series.

**Comment by Elwador** [comment]
when the series folder path is used it would be possible (and would probably also be the best way) - but like you said since everyone can add folders to the filename as they like and maybe don't directly set the folder path for each series it would be hard
![image](https://github.com/user-attachments/assets/31916eb9-acca-4085-8068-b49bb6b8065a)

also saving the location when the episode is downloaded could work but also always bares the risk that the files get moved or anything changes in the path every "link" is broken

you can do `\\` with the code block

**Comment by Vorffeed** [comment]
Thank you, it's going perfect 👍
