### ISSUE TITLE
Video Metadata

### ISSUE THREAD

**Issue by kikoreta** [Crunchy-DL/Crunchy-Downloader#18]
Could adding the program/season/episode/episode name to the video metadata title and the episode description to metadata description be posible?

**Comment by Elwador** [comment]
@kikoreta is now in the new version [v1.4.25](https://github.com/Crunchy-DL/Crunchy-Downloader/releases/tag/v1.4.25)

**Comment by kikoreta** [comment]
Thanks, downloaded and tested, works like a charm, adding a language selector for the description could be possible?

**Comment by kikoreta** [comment]
Tested and working correctly, thanks

**Comment by Anime1998** [comment]
Hi, I just want to ask where the episode description is saved to the metadata? I use v1.4.29 and enabled episode description in the settings and if i download something there is no description saved? Could it be because it don´t work with german language? Am I just too stupid for this or is it really not working properly? In case 1, it would be nice if someone could enlighten me :D

![grafik](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/174193982/e6660b30-09f9-4373-bf27-ec69a0a34608)

![grafik](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/174193982/5920fae5-9bb3-4419-a72e-b1ef124dfadb)

![grafik](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/174193982/75f17180-7ca8-42fb-8a94-a97a2496057b)

![grafik](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/174193982/ca6c59c1-691f-49ab-844c-efa29b9409dd)

**Comment by Elwador** [comment]
tthe problem here is that you are creating mp4 files - i haven't added the description muxing to that

**Comment by Anime1998** [comment]
Ah, makes sense.

**Comment by Elwador** [comment]
but i just added it so it's in the next release

**Comment by Anime1998** [comment]
nice, thank you very much 👍
