### ISSUE TITLE
Sonarr / Auto-Add missing episode

### ISSUE THREAD

**Issue by Nonobis** [Crunchy-DL/Crunchy-Downloader#19]
I don't known if you can search for specific episode or show in cruchycroll .... Could you add automatically missing episode from sonarr in dowload list ?

**Comment by Elwador** [comment]
i think it would be possible to search for a show and from there check the episodes but everything related to sonarr is not 100% accurate because CR names stuff differently
the easiest way to get missing episodes currently is to just add a series to the history (maybe mark the last episode that was downloaded) -> press refresh all -> add to queue
maybe also enable the "Use Sonarr numbering" in the settings

**Comment by Nonobis** [comment]
thanks will try your tips for now:) Thanks for your time. And great app
