### ISSUE TITLE
Possible bug(s) downloading from new History Table

### ISSUE THREAD

**Issue by petenun** [Crunchy-DL/Crunchy-Downloader#24]
Using 1.4.28

I'll start with the smallest one first. When clicking on the download link next to an episode in History, it adds the title to the queue correctly, but collapses the list so that you would need to re-expand to get a second episode from the series. 

Then I foolishly selected a couple episodes using the green checkmark and hit the "Add to Queue" button at the top. All of a sudden every episode from every series was being added to the queue. Probably not the desired result.

![image](https://github.com/Crunchy-DL/Crunchy-Downloader/assets/55004359/fa5560f3-cdb3-4c13-a42c-fa3f2780db14)

**Comment by Elwador** [comment]
"Then I foolishly selected a couple episodes using the green checkmark and hit the "Add to Queue" button at the top. All of a sudden every episode from every series was being added to the queue. Probably not the desired result."
it is the desired result because the green checkmark only shows if you have downloaded the episode previously you can also click it to mark it that you have already downloaded it

**Comment by petenun** [comment]
Thanks for addressing the first issue. As for the second, um, user error??  :-)

**Comment by Elwador** [comment]
😄 the add to queue is meant to add all new episodes (orange mark) to the queue  - really nice when you are up to date with downloading everything and you only have to go into the history press "refresh" and it checks all series for new episodes and after that you press "Add to Queue" and it adds all the new episodes to the queue
