### ISSUE TITLE
[Bug] The Downloader stops responding and crashes/closes itself when downloading Demon Slayer S04E03

### ISSUE THREAD

**Issue by ben10092001** [Crunchy-DL/Crunchy-Downloader#88]
The Downloader stops responding and crashes/closes itself when downloading **Demon Slayer S04E03 (Hashira Training Arc)**
The dubs I have selected are en-US, ja-JP, hi-IN, ta-IN, te-IN
The softsub I have selected is only en-US. No hardsubs enabled.
Video and audio quality have been set to best and chapters are also turned on
Stream endpoint is web/firefox. Also I have tried web/chrome and web/edge. But same problem occurs again.

All other episodes download normally as expected. But this episode specifically crashes the downloader.
I have tried multiple times still the same result every time.

**Comment by Elwador** [comment]
> 4. **Check the Windows Event Log (if the program crashes)**
>    - If the program crashes, please check the Windows Event Log for any related error messages (.NET runtime) and include that information in your issue report.

since i can't reproduce it i definetly need this

**Comment by Vorffeed** [comment]
With my usual configuration it does not fail, have you checked on the web that it is not a failure of some audio or subtitle, because yesterday I was fighting with the program, because I did not understand why the episode 5 of Saint Seiya of season one, despite having configured the audio in Japanese and the subtitle in Spanish I got audio in English and no subtitles even though the program said it was fine, and in the end it was a thing of the Crunchyrrol website that the audio and subtitles of that episode were wrong xd 

![image](https://github.com/user-attachments/assets/97ad6170-4777-4cee-937e-305b7ba95cbf)

**Comment by ben10092001** [comment]
I don't know what was the reason but the update v1.5.25 seems to have fixed this issue. Thank you so much.
