### ISSUE TITLE
[Bug] Doesn't download CC for certain anime

### ISSUE THREAD

**Issue by The-Math-God** [Crunchy-DL/Crunchy-Downloader#97]
hi pretty simple while it does download the CC from most of the anime
some anime don't cowboy bebop is one such example 
and i know for a fact it has CC

**Comment by Vorffeed** [comment]
I'll leave it here so I don't have to open a new thread.
I don't know what's going on, I thought it had been solved, but lately the last episodes that are being broadcasted don't download the CC and on the web you can see that they have them.

**Comment by Elwador** [comment]
it says "fixed - release coming soon"

**Comment by Vorffeed** [comment]
I wasn't referring to this one, I was referring to another post I read where they had fixed the issue of getting CC as they had stopped doing it and it was fixed with the update and the topic was closed last week or so, I posted here because I saw there was already a similar one, and not open a new one.
